# Generated by Django 5.2.7 on 2025-10-09 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Publication",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=150, verbose_name="Заголовок")),
                ("text", models.TextField(verbose_name="Текст")),
                ("preview", models.ImageField(null=True, upload_to="images/blog/preview/", verbose_name="Превью")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("is_published", models.BooleanField(default=True, verbose_name="Признак публикации")),
                ("views_counter", models.IntegerField(default=0, verbose_name="Счетчик просмотров")),
            ],
            options={
                "verbose_name": "публикация",
                "verbose_name_plural": "публикации",
                "db_table": "publications",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to="images/blog/photos/", verbose_name="Фото")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Номер")),
                ("caption", models.CharField(blank=True, max_length=200, null=True, verbose_name="Подпись")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                (
                    "publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="blog.publication",
                        verbose_name="Статья",
                    ),
                ),
            ],
            options={
                "verbose_name": "фотография",
                "verbose_name_plural": "фотографии",
                "db_table": "photos",
                "ordering": ["order"],
            },
        ),
    ]
