# Generated by Django 5.2.7 on 2025-10-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="rubric",
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name="Рубрика"),
        ),
    ]
