# Generated by Django 5.2.7 on 2025-11-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_publication_preview_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="publication_type",
            field=models.CharField(
                choices=[("full", "Статья для блога"), ("small", "Заметка"), ("news", "Новость")],
                default="full",
                max_length=10,
                verbose_name="Тип статьи",
            ),
        ),
    ]
