worker_processes auto;
pid /run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    types {
        text/css css;
        application/javascript js;
        image/jpeg jpg jpeg;
        image/png png;
        image/svg+xml svg;
        font/woff woff;
        font/woff2 woff2;
    }
    upstream django {
        server varnitsa_web:8000;
    }
    # Обработка HTTP-запросов, редирект на HTTPS, если задан домен
    server {
        listen 80;
        # Используем переменную DOMAIN, задаваемую в docker-compose.yml, а если она не задана - любой хост
        server_name ${DOMAIN} _;

        # Certbot использует эту директорию только если DOMAIN задан
        location /.well-known/acme-challenge/ {
            # Проверяем, что DOMAIN задан (не равен "_")
            if ($server_name = "_") {
                return 404;
            }
            root /var/www/certbot;
        }
        location /static/ {
            alias /app/staticfiles/;
            expires 1y;
            add_header Cache-Control "public, immutable";
        }

        location /media/ {
            alias /app/media/;
            expires 1y;
            add_header Cache-Control "public";
        }
        location / {
            # проксируем запросы на джанго-приложение
            proxy_pass http://django;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Host $http_host;
        }
    }
}
