worker_processes auto;
pid /run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    upstream django {
        server web:8000;
    }
    # Обработка HTTP-запросов, редирект на HTTPS, если задан домен
    server {
        listen 80;
        # Используем переменную DOMAIN, задаваемую в docker-compose.yml, а если она не задана - любой хост
        server_name ${DOMAIN} _;

        # Certbot использует эту директорию только если DOMAIN задан
        location /.well-known/acme-challenge/ {
            # Проверяем, что DOMAIN задан (не равен "_")
            if ($server_name = "_") {
                return 404;
            }
            root /var/www/certbot;
        }
        location / {
            # проксируем запросы на джанго-приложение
            proxy_pass http://django;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Host $http_host;
        }
    }
}
