# Generated by Django 5.2.7 on 2025-10-19 11:12
from django.contrib.postgres.operations import BtreeGinExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_remove_product_category_product_category"),
    ]

    operations = [
        BtreeGinExtension(),
    ]
