# Generated by Django 5.2.7 on 2025-10-19 11:16

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_auto_20251019_1412"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="product",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["product_name", "trade_mark", "specification", "description"],
                name="product_gin_idx",
                opclasses=["gin_trgm_ops", "gin_trgm_ops", "gin_trgm_ops", "gin_trgm_ops"],
            ),
        ),
    ]
